# Generated by Django 5.0.3 on 2024-03-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficina', models.CharField(choices=[('gasolina', 'GASOLINA'), ('diesel', 'DIESEL'), ('posto', 'POSTO'), ('eletrica', 'ELÉTRICA'), ('montagem', 'MONTAGEM'), ('motos', 'MOTOS'), ('superestruturas', 'SUPERESTRUTURAS'), ('borracharia', 'BORRACHARIA'), ('pintura', 'PINTURA')], default='', max_length=30)),
                ('oss', models.CharField(max_length=9)),
                ('prefixo', models.CharField(max_length=9)),
                ('modelo', models.CharField(max_length=20)),
                ('fornecedor', models.CharField(choices=[('gilson', 'GILSON'), ('partslub', 'PARTS LUB')], default='', max_length=30)),
                ('data_envio', models.DateField()),
                ('data_recebimento', models.DateField()),
                ('responsavel_recebimento', models.CharField(max_length=9)),
                ('mecanico_requerente', models.CharField(max_length=9)),
                ('nota_fiscal', models.CharField(max_length=9)),
            ],
        ),
    ]
