# Generated by Django 5.0.3 on 2024-03-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_oficina', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedido',
            new_name='Pedido2024',
        ),
    ]
