# Generated by Django 5.0.3 on 2024-03-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_oficina', '0004_alter_pedido2024_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido2024',
            name='modelo',
            field=models.CharField(choices=[('1', '1030'), ('2', '13.18'), ('3', '15.18'), ('4', '15.190 CRM 4X2'), ('5', '17.21'), ('6', '170 E 22'), ('7', '17250 CNC'), ('8', '19.390 4X2'), ('9', '2031 ACTROS'), ('10', '31.32'), ('11', '31.330  6X4'), ('12', '3331 ACTROS'), ('13', '380T38'), ('14', '4140 ACTROS'), ('15', '70C16HDCS'), ('16', 'ACCELO 815'), ('17', 'ARGO '), ('18', 'ARROW XT'), ('19', 'ATEGO 1725'), ('20', 'ATEGO 1726/42'), ('21', 'ATEGO 1729'), ('22', 'ATEGO 3330CE'), ('23', 'ATEGO 823'), ('24', 'C4'), ('25', 'CARGO 1519 S'), ('26', 'CARGO 2622 E'), ('27', 'CARGO 712'), ('28', 'CARRETA'), ('29', 'CB 500X'), ('30', 'CRUZE LT'), ('31', 'DAILY 70C16'), ('32', 'DAILY 70C16HDCS'), ('33', 'FURGOVAN 6000'), ('34', 'G650 GS'), ('35', 'GIMAEX P360'), ('36', 'GRAND VIA'), ('37', 'GRANMIDI '), ('38', 'HILUX '), ('39', 'INDUSCAR GI R 500'), ('40', 'ITURRI P320'), ('41', 'ITURRI P360'), ('42', 'JACINTO P-360'), ('43', 'KANGOO '), ('44', 'L200 TRITON'), ('45', 'L200 TRITON 3.2 D'), ('46', 'LOGAN EXP 16'), ('47', 'M.BENZ 516 MOBILE S. CM'), ('48', 'MASCA GRANMINI O'), ('49', 'O 500RSD'), ('50', 'P 440 MAGIRUS'), ('51', 'PAJERO HD'), ('52', 'PALIO ESSENCE 1.6'), ('53', 'PIÁ'), ('54', 'RANGER '), ('55', 'RD1 158'), ('56', 'RENEGADE 1.8 AUTOM.'), ('57', 'S10 LT '), ('58', 'S10 LTZ '), ('59', 'SANDERO DYNA 1.6'), ('60', 'SPRINTER'), ('61', 'SPRINTER 415'), ('62', 'SPRINTER C'), ('63', 'TRANSIT 350L'), ('64', 'UNO '), ('65', 'VOLARE A6'), ('66', 'XRE 300'), ('67', 'XT 660R'), ('68', 'XTZ 250')], default='', max_length=30),
        ),
    ]
