# Generated by Django 5.0.3 on 2024-03-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_oficina', '0007_alter_pedido2024_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido2024',
            name='pedido',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
