# Generated by Django 5.0.3 on 2024-03-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_oficina', '0008_alter_pedido2024_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido2024',
            name='data_recebimento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='pedido2024',
            name='mecanico_requerente',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='pedido2024',
            name='nota_fiscal',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='pedido2024',
            name='oss',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='pedido2024',
            name='responsavel_recebimento',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
