# Generated by Django 5.0.3 on 2024-03-28 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_oficina', '0009_alter_pedido2024_data_recebimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido2024',
            name='oss',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_os_format', message='Formato invalido. Correto: 1234/2024', regex='\\d{1,4}\\s?\\/\\s?\\d{2,4}')]),
        ),
    ]
